# Generated by Django 6.0.2 on 2026-02-06 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Adresse e-mail"),
                ),
                (
                    "password",
                    models.CharField(max_length=128, verbose_name="Mot de passe"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=199,
                        max_digits=8,
                        verbose_name="Montant payé",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'inscription"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Progress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_module",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Dernier module validé"
                    ),
                ),
                (
                    "last_section",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Dernière partie"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière mise à jour"
                    ),
                ),
                (
                    "enrollment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="core.enrollment",
                    ),
                ),
            ],
        ),
    ]
